apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    group: {{ .Values.app.name }}
    obs: appd
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        group: {{ .Values.app.name }}
        obs: appd
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          volumeMounts:
          - name: log-volume
            mountPath: /opt/apps/rms/{{ .Values.app.name }}/logs
          - name: secrets-po-inline
            mountPath: "/mnt/secrets-po"
            readOnly: true
          - name: config-volume
            mountPath: /script/start.sh
            subPath: start.sh
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "10"]
      terminationGracePeriodSeconds: 60
      
      volumes:
      - name: log-volume
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }}
      - name: config-volume
        configMap:
          name: {{ .Values.app.name }}-configmap
          defaultMode: 0755
      - name: secrets-po-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "po-kv-secret"
          nodePublishSecretRef:
            name: secrets-po-creds
      
      restartPolicy: Always
      # imagePullSecrets:
      # - name: {{ .Values.imagePullSecrets }}
