apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  # type: LoadBalancer
  selector:
    app: {{ .Values.app.name }}
  ports:
    - name: service
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
# status:
#   loadBalancer:
#     ingress:
#     - ip: {{ .Values.loadBalancerIP }}     